---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 1311-pv
spec:
  storageClassName: "standard"
  capacity:
    storage: 2Gi
  hostPath:
    path: "/host/"
  accessModes:
    - ReadWriteMany

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-pvc
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
